### ISSUE TITLE
latestTag should be reachable tag aware

### ISSUE THREAD

**Issue by dkichler** [sbt/sbt-autoversion#107]
This scenario arises when there exists branches for continuing to maintain multiple version streams.  As an example:

Some breaking changes in a theoretical repo are introduced and released, causing a version bump from 1.x to 2.0.0 on the master branch (standard trunk-based development model).  Maintainers would like to continue supporting 1.x and so create a branch `1.x+` for this purpose.  A couple of bugfixes are applied to `1.x+` but when exercising the release process against that branch, `latestTag` will still select the `v2.0.0` tag from master as 'latest', failing to consider that `v2.0.0` is not 'reachable' from the HEAD of `1.x+`

`latestTag` should be 'reachable' aware, which should be possible through using commands like git describe

**Comment by dkichler** [comment]
@pdalpra is there any appetite/support for this change?

**Comment by dkichler** [comment]
(or perhaps the most likely, just a lack of spare cycles? 😉 )

**Comment by pdalpra** [comment]
My bad, forgot to answer your message!
Yeah right now I lack spare time, dad of a 1 month old baby 😅😅

**Comment by dkichler** [comment]
In that case, please do ignore this ticket and PR (for the time being 😉) and spend as many moments with your baby as possible  🙂

**Comment by dkichler** [comment]
@pdalpra Thought I would check in on this issue.  We've been using a fork internally that addresses this issue, but have reached a point where we'd like to use this plugin as a dependency in another plugin we're intending to open source.  Would be ideal if we could get this behaviour into this public version so the new plugin could depend on this original rather than our fork.

**Comment by dkichler** [comment]
I was going to suggest that as an option, if you were amenable to it, which it sounds like you are.  Would be happy to assume that role, please feel free to take whatever actions are necessary from your end.  Thanks for the quick response and suggestion!

**Comment by dkichler** [comment]
I think https://github.com/sbt/sbt-autoversion/pull/154 gets us most of the way there, is all that's left to extend write privileges?

**Comment by pdalpra** [comment]
Yup, I'll ask the sbt organization maintainers to give your access to the repository, though there is something a bit more problematic: to be able to releade from just a tag release, I need to setup Github actions, which I can't do right now, I'll ask if it's possible.

**Comment by pdalpra** [comment]
FYI, just [asked on Twitter](https://twitter.com/pierre_dalpra/status/1572217186021933056).
