### ISSUE TITLE
org.scala-sbt organization

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-autoversion#8]
I noticed that sbt-autoversion uses `org.scala-sbt` organization.
We want to reserve the use of `org.scala-sbt` for sbt uses, so please use `com.github.sbt` or some other domain name please.

We are working on dependency resolution optimization, `org.scala-sbt` artifacts might not be included into the resolution (since sbt itself is already resolved by the launcher once), which affects this plugin.

**Comment by pdalpra** [comment]
Will tackle it ASAP, thanks for the notice !
